---
- hosts: local
  gather_facts: no
  tasks:
    - add_host:
        name: "{{ raspberry_ip }}"
        groups: raspberry

- hosts: raspberry
  vars_files:
    - runeaudio-vars.yml
  tasks:
    - name: setup display
      include_role:
        name: setup-display
      vars:
        - remote: true
        - boot_mount: /boot
