---
- hosts: local
  gather_facts: no
  tasks:
    - add_host:
        name: "{{ raspberry_ip }}"
        groups: raspberry

- hosts: raspberry
  vars_files:
    - runeaudio-vars.yml
  tasks:
    - name: Disable systemd-networkd-wait-online
      shell: systemctl disable systemd-networkd-wait-online

    - name: fix localhost in nginx
      shell: "sed -i 's/localhost/127.0.0.1/g' /etc/nginx/nginx-prod.conf /etc/nginx/nginx.conf"

    - name: setup display
      include_role:
        name: setup-display
      vars:
        - remote: true
        - boot_mount: /boot

    - name: reboot
      shell: "reboot"
