---
- hosts: local
  gather_facts: no
  tasks:
    - add_host:
        name: "{{ raspberry_ip }}"
        groups: raspberry

- hosts: raspberry
  vars_files:
    - runeaudio-vars.yml
  tasks:
    - name: init pacman for Runeaudio
      include_role:
        name: runeaudio-pacman-init
    - name: pacman custom packages for Runeaudio
      include_role:
        name: runeaudio-pacman-custom-packages
    - name: configure packages
      include_role:
        name: runeaudio-configure-packages
    - name: build AUR packages
      include_role:
        name: archlinux-build-aur
    - name: configure plymouth-lite
      include_role:
        name: runeaudio-plymouth-lite
    - name: remove unused packages
      include_role:
        name: runeaudio-remove-packages
    - name: shutdown
      shell: "shutdown -h now"
