---
- hosts: local
  gather_facts: no
  tasks:
    - add_host:
        name: "{{ raspberry_ip }}"
        groups: raspberry

- hosts: raspberry
  vars_files:
    - runeaudio-vars.yml
  tasks:
#    - name: init pacman for Runeaudio
#      include_role:
#        name: runeaudio-pacman-init
    - name: pacman custom packages for Runeaudio
      include_role:
        name: runeaudio-pacman-custom-packages
    - name: configure packages
      include_role:
        name: runeaudio-configure-packages
    - name: build matchbox
      include_role:
        name: runeaudio-build-matchbox
#    - name: ply-image
