
- parted:
    device: "/dev/{{ local_sd.blockdevice }}"
    unit: MiB
  register: blk_info
  become: yes

- name: umount boot partition
  shell: "umount /dev/{{ local_sd.bootpart }}"
  become: yes
  ignore_errors: yes

- name: umount root partition
  shell: "umount /dev/{{ local_sd.rootpart }}"
  become: yes
  ignore_errors: yes

- name: remove partitions
  parted:
    device: "/dev/{{ local_sd.blockdevice }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
   - "{{ blk_info.partitions }}"
  become: yes

- name: create boot partition 
  parted:
    device: "/dev/{{ local_sd.blockdevice }}"
    number: 1
    state: present
    part_end: 105MiB
  become: yes

- name: set boot partition type
  shell: "sfdisk --part-type /dev/{{ local_sd.blockdevice }} 1 c"
  become: yes

- name: create root partition 
  parted:
    device: "/dev/{{ local_sd.blockdevice }}"
    number: 2
    state: present
    part_start: 106MiB
  become: yes

- name: create boot filesystem
  filesystem:
    dev: "/dev/{{ local_sd.bootpart }}"
    fstype: vfat
    force: yes
  become: yes

- name: create root system
  filesystem:
    dev: "/dev/{{ local_sd.rootpart }}"
    fstype: ext4
    force: yes
  become: yes
