---

- name: mount partitions
  include_role:
    name: mount-sd-partitions

- name: HDMI group
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^hdmi_group"
    line: "hdmi_group={{ hdmi.group }}"
  become: yes

- name: HDMI mode
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^hdmi_mode"
    line: "hdmi_mode={{ hdmi.mode }}"
  become: yes

- name: HDMI drive
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^hdmi_drive"
    line: "hdmi_drive={{ hdmi.drive }}"
  become: yes

- name: HDMI cvt
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^hdmi_cvt"
    line: "hdmi_cvt {{ hdmi.cvt }}"
  become: yes

- name: overscan
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^disable_overscan"
    line: "disable_overscan 1"
  become: yes

- name: HDMI ignore_cec
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^hdmi_ignore_cec"
    line: "hdmi_ignore_cec 1"
  become: yes

- name: gpu_mem
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^gpu_mem"
    line: "gpu_mem 16"
  become: yes

- name: max_usb_current
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^max_usb_current"
    line: "max_usb_current=1"
  become: yes

- name: umount partitions
  include_role:
    name: umount-sd-partitions

