---

- name: chown sources to user
  shell: "chown -R http /usr/local/src/{{ item.name }}/"

- name: "check if {{ item.name }} is built"
  find:
    path: "/usr/local/src/{{ item.name }}/"
    pattern: "{{ item.short }}*{{ arch }}.pkg.tar.xz"
  register: existing

- name: "install {{ item.name }} build dependancies "
  shell: "pacman -S --needed --noconfirm {% for package in item.make_depends %} {{ package }} {% endfor %}"
  when: existing.matched == 0 and item.make_depends is defined

- name: "build {{ item.name }}"
  shell: "cd /usr/local/src/{{ item.name }} && sudo -u http makepkg -s"
  when: existing.matched == 0

- name: "install {{ item.name }}"
  shell: "pacman -U /usr/local/src/{{ item.name }}/{{ item.short }}*{{ arch }}.pkg.tar.xz --noconfirm"
