---

- name: mount partitions
  include_role:
    name: mount-sd-partitions

- name: dtparam audio
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^dtparam=audio="
    line: "dtparam=audio=on"
  become: yes

- name: stop auditd from spamming dmesg
  lineinfile:
    dest: "{{ boot_mount }}/cmdline.txt"
    create: yes
    regexp: "^root"
    line: "root=/dev/mmcblk0p2 rw rootwait console=ttyAMA0,115200 console=tty3 selinux=0 plymouth.enable=0 fsck.repair=yes smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 kgdboc=ttyAMA0,115200 elevator=noop audit=0 quiet consoleblank=0 loglevel=0 logo.nologo"
  become: yes

- name: issue
  template:
    src: issue.config
    dest: "{{ root_mount }}/etc/issue"
  become: yes

- name: eth0
  template:
    src: eth0.j2
    dest: "{{ root_mount }}/etc/netctl/eth0"
  become: yes

- name: umount partitions
  include_role:
    name: umount-sd-partitions

