---

- name: mount partitions
  include_role:
    name: mount-sd-partitions

- name: dtparam audio
  lineinfile:
    dest: "{{ boot_mount }}/config.txt"
    regexp: "^dtparam=audio="
    line: "dtparam=audio=on"
  become: yes

- name: umount partitions
  include_role:
    name: umount-sd-partitions

