---

- name: get arch
  include_role:
    name: archlinux-get-arch

- name: setup sudo to http
  template:
    src: sudoers.d.http
    dest: /etc/sudoers.d/http

- name: install necessary packages
  shell: "which makepkg || pacman -S {{ item }} --noconfirm"
  with_items:
    - base-devel

- name: create sources directory
  file:
    path: "{{source_directory }}"
    state: directory

- name: get package source
  get_url:
    url: "https://aur.archlinux.org/cgit/aur.git/snapshot/{{ item }}.tar.gz"
    dest: "{{source_directory }}/"
    timeout: 1800
  with_items:
    - libmatchbox
    - matchbox-window-manager
    - plymouth-lite-rbp-git

- name: untar sources
  unarchive:
    remote_src: true
    src: "{{source_directory }}/{{ item }}.tar.gz"
    dest: "{{source_directory }}/"
  with_items:
    - libmatchbox
    - matchbox-window-manager
    - plymouth-lite-rbp-git

- name: chown sources to user
  shell: "chown -R http {{source_directory }}/"

- name: build packages
  include_role:
    name: archlinux-build-package
  with_items:
    - name: libmatchbox
      pkgname: libmatchbox
      make_depends:
        - xsettings-client
        - startup-notification
    - name: matchbox-window-manager
      pkgname: matchbox-window-manager
    - name: plymouth-lite-rbp-git
      pkgname: plymouth-lite-rbp-git
