---

- name: setup sudo to http
  template:
    src: sudoers.d.http
    dest: /etc/sudoers.d/http

- name: install necessary packages
  shell: "which makepkg || pacman -S {{ item }} --noconfirm"
  with_items:
    - base-devel

- name: create sources directory
  file:
    path: /usr/local/src
    state: directory

- name: get package source
  get_url:
    url: "https://aur.archlinux.org/cgit/aur.git/snapshot/{{ item }}.tar.gz"
    dest: /usr/local/src/
    timeout: 1800
  with_items:
    - libmatchbox
    - matchbox-window-manager
    - plymouth-lite-rbp-git

- name: untar sources
  unarchive:
    remote_src: true
    src: "/usr/local/src/{{ item }}.tar.gz"
    dest: /usr/local/src/
  with_items:
    - libmatchbox
    - matchbox-window-manager
    - plymouth-lite-rbp-git

- name: patch PKGBUILD
  lineinfile: 
    dest: "/usr/local/src/{{ item }}/PKGBUILD"
    regexp: "^arch="
    line: "arch=('{{ arch }}')"
  with_items:
    - libmatchbox
    - matchbox-window-manager
    - plymouth-lite-rbp-git

- name: chown sources to user
  shell: "chown -R http /usr/local/src/"
  warn: false

- name: build packages
  include_role:
    name: archlinux-build-package
  with_items:
    - name: libmatchbox
      short: "libmatchbox"
      make_depends:
        - xsettings-client
        - startup-notification
    - name: matchbox-window-manager
      short: "matchbox-window-manager"
    - name: plymouth-lite-rbp-git
      short: plymouth-lite-rbp-git
