---

- name: synchronise sources directory
  synchronize:
    src: packages/
    dest: "{{source_directory }}"

#- name: remove standard kernel
#  shell: "(pacman -Q linux-raspberrypi && pacman -R linux-raspberrypi --noconfirm) || true"

- name: build packages
  include_role:
    name: archlinux-build-package
  with_items:
    - "{{ sources }}"
