---

- name: synchronise sources directory
  synchronize:
    src: packages/
    dest: /usr/local/src

- name: build packages
  include_role:
    name: archlinux-build-package
  with_items:
    - "{{ sources }}"

#- name: remove standard kernel
#  shell: "(pacman -Q linux-raspberrypi && pacman -R linux-raspberrypi --noconfirm) || true"
#
#- name: build, pass 3
#  shell: "pacman -Q {{ item.short }} || pacman -U /usr/local/src/{{ item.name }} --noconfirm {% if item.flags is defined %} {{ item.flags }} {% endif %}"
#  when: item.pass == 3
#  with_items:
#    - "{{ sources }}"
#
#- name: remove sources directory
#  file:
#    path: /usr/local/src
#    state: absent
