---

- name: mount partitions
  include_role:
    name: mount-sd-partitions

- name: cleanup source directory
  file:
    path: "{{ root_mount }}/{{ source_directory }}"
    state: absent
  become: yes
  when: cleanup_sources is defined and cleanup_sources == true

- name: cleanup potential ssh public keys
  file:
    path: "{{ root_mount }}//root/.ssh"
    state: absent
  become: yes

- name: umount partitions
  include_role:
    name: umount-sd-partitions
