---

- name: install required components
  apt:
    name: ["coreutils", "mount", "tar", "gzip", "sshpass"]
    state: present
  become: yes

- name: create download directory
  tempfile:
    prefix: raspberry-image
    state: directory
  register: downloaddir

- name: download image
  get_url:
    url: "{{ distribution.url }}"
    dest: "{{ downloaddir.path }}"
    timeout: 1800
  register: downloaded

- name: mount partitions
  include_role:
    name: mount-sd-partitions

- name: unarchive url
  unarchive:
    src: "{{ downloaded.dest }}"
    dest: "{{ root_mount }}"
  ignore_errors: yes
  become: yes

- name: move boot files to boot partition
  shell: "mv -f {{ root_mount }}/boot/* {{ boot_mount }}/"
  become: yes

- name: fix fstab
  lineinfile:
    path: "{{ root_mount }}/etc/fstab"
    regexp: "^/dev/{{ remote_sd.bootpart }}"
    line: "/dev/{{ remote_sd.bootpart }}  /boot   vfat    defaults,rw        0       0"
  become: yes

- name: umount partitions
  include_role:
    name: umount-sd-partitions

- name: remove download directory
  file:
    path: "{{ downloaddir.path }}"
    state: absent