---

- name: update pacman
  shell: "pacman -Syu --noconfirm"

- name: install necessary packages
  shell: "pacman -S --needed --noconfirm {% for item in packages %} {{ item }} {% endfor %}"
  when: packages is defined
