---

- name: update pacman
  shell: "pacman -Syu --noconfirm"

- name: remove unnecessary packages
  shell: "pacman -R --noconfirm {% for item in removed_packages %} {{ item }} {% endfor %} || true"
  when: removed_packages is defined

- name: install necessary packages
  shell: "pacman -S --needed --noconfirm {% for item in packages %} {{ item }} {% endfor %}"
  when: packages is defined
