---

- name: mount partitions
  include_role:
    name: mount-sd-partitions

- name: change root password
  lineinfile:
    dest: "{{ root_mount }}/etc/shadow"
    regexp: "^root"
    line: "root:{{ shadow.root }}:17916::::::"
  become: yes

- name: change alarm password
  lineinfile:
    dest: "{{ root_mount }}/etc/shadow"
    regexp: "^alarm"
    line: "alarm:!!:17916::::::"
  become: yes

- name: allow root SSH login
  lineinfile:
    dest: "{{ root_mount }}/etc/ssh/sshd_config"
    regexp: "PermitRootLogin"
    line: "PermitRootLogin yes"
  become: yes

- name: allow password SSH login
  lineinfile:
    dest: "{{ root_mount }}/etc/ssh/sshd_config"
    regexp: "PasswordAuthentication"
    line: "PasswordAuthentication yes"
  become: yes

- name: umount partitions
  include_role:
    name: umount-sd-partitions

